version: '3.8'

services:
  web:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      - DJANGO_SECRET_KEY=super-secret-key
      - DEBUG=1
      - ALLOWED_HOSTS=localhost,127.0.0.1
